version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - training-log-v2-app
    volumes:
      - postgres-data:/data/postgres

  web:
    image: training-log-v2-web
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    ports:
      - "8085:8085"
    networks:
      - training-log-v2-app
    depends_on:
      - postgres

networks:
  training-log-v2-app:
    driver: bridge

volumes:
  postgres-data:
    driver: local
